services:
  hefesto-front:
    container_name: hefesto-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9987:4200"  # Porta externa 9987 -> porta interna 4200 do ng serve
    restart: on-failure
