version: '3.8'

services:
  hefesto-front:
    container_name: hefesto-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9987:4200"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '1'
