version: '3.8'

services:
  hefesto-front:
    container_name: hefesto-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9187:4200"  # Porta externa 9987 -> Porta Angular 4200
    restart: on-failure
